### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by itaymesh** [opengento/magento2-downgrade-ee-ce#10]
Hi,
I would like to know whether this repo is still maintained and, if so, what the last Magento version it was tested.
Cheers
Itay

**Comment by thomas-kl1** [comment]
Hello @itaymesh 

I know that scripts from this repo are still actively used by co-workers. Also note that these scripts are given in order to help you, but some additional work may still be needed, depending of your MySQL engine and Magento version / third parties modules.
Feel free to contribute if you can 😃 
I'm closing this issue as it's not related to a bug. You can start a thread here if you need to talk about the tool: https://github.com/opengento/magento2-downgrade-ee-ce/discussions
