### ISSUE TITLE
Migrate 2.4.* version

### ISSUE THREAD

**Issue by Khaledhesham** [opengento/magento2-downgrade-ee-ce#6]
Does this script work for 2.4 version? if not then is there any help that you could provide as info so I add more handling to it?

**Comment by thomas-kl1** [comment]
Hi @Khaledhesham it has not been tested with 2.4 so I can't say. however you could try first if the migration run fine with the declarative schema. If not you can try these scripts. Then You'll have to check if everything works fine or update the script for missing points

**Comment by thomas-kl1** [comment]
@Khaledhesham If you have any question or need help to contribute, feel free to ask me on this thread :)

**Comment by kylianleemkuil** [comment]
Hi @Khaledhesham , @thomas-kl1 ,

I was wondering if you got it working on your 2.4 version. I also tried to downgrade Magento 2.4 EE to CE and got stuck on categories and product tables where it had problems on constraints with exisiting data of multiple values being te same.

For example here is this constraint:
``ADD CONSTRAINT `CATALOG_PRODUCT_ENTITY_DATETIME_ENTITY_ID_ATTRIBUTE_ID_STORE_ID` UNIQUE KEY (`entity_id`,`attribute_id`,`store_id`) ``

And because of rules like this it somehow has multiple entity_id with store_id in there and this gives errors with existing data:
``UPDATE `catalog_product_entity_datetime` v INNER JOIN `catalog_product_entity` e ON v.`row_id` = e.`row_id`
SET v.`entity_id` = e.`entity_id`
WHERE 1;``

So im wondering how did you tackled this?

**Comment by thomas-kl1** [comment]
@kylianleemkuil you need first to cleanup the catalog_product_entity table. You have to (regarding your needs) only one occurence (one row) per entity_id (so you have to keep only one row_id per records of entity_id).

You can try this sql:

```sql
DELETE FROM catalog_product_entity WHERE row_id NOT IN (SELECT MAX(row_id) FROM catalog_product_entity  GROUP BY entity_id)
```

**Comment by kylianleemkuil** [comment]
@thomas-kl1 seems that I got the products.sql working now and also executed the same for categories:
```sql
DELETE FROM catalog_category_entity WHERE row_id NOT IN (SELECT MAX(row_id) FROM catalog_category_entity GROUP BY entity_id)
```
I still get the next error:
``#1062 - Double entry '0-46-0' for searchkey 'CATALOG_CATEGORY_ENTITY_INT_ENTITY_ID_ATTRIBUTE_ID_STORE_ID'``

So there are still doubles in that table over those 3 columns that it is trying to put a constraint on. Any solution how to safely remove those or prevent it to add doubles?

**Comment by thomas-kl1** [comment]
I don't know why you have the composition 0-46-0 which looks like entity id = 0 attribute id = 46 store id = 0
I don't think that entity id 0 is valid. Anyway could you check if you also have duplicates in eav values tables of the catalog_product entity? (see catalog_product_entity_*)

**Comment by kylianleemkuil** [comment]
![image](https://user-images.githubusercontent.com/17156823/142430285-6c879a86-491a-47f7-8b1c-38a81fd489cb.png)
Apparently a lot of values(like 40) in catalog_category_entity_* are set to entity_id = 0 when I run the first part of the category.sql file. Is this because it can't find the 'catalog_category_entity' entity_id and then sets it to 0?

In "catalog_product_entity_*" I apparently don't have doubles because the product.sql runs makes the constraints without any issues

**Comment by thomas-kl1** [comment]
Entity_id looks weird to me as it shouldn't even exists at all, unless I'm not aware of some specific development in your project. I would suggest you tu. Remove anything that match entity_id=0. Also you can check if that product actually exists or not from the BO

**Comment by kylianleemkuil** [comment]
@thomas-kl1 Got it working now I just executed the following before the constraints are set:

```sql
DELETE FROM `catalog_category_entity_datetime` WHERE row_id NOT IN (SELECT MAX(row_id) FROM catalog_category_entity GROUP BY entity_id) ORDER BY `entity_id` ASC;

DELETE FROM `catalog_category_entity_decimal` WHERE row_id NOT IN (SELECT MAX(row_id) FROM catalog_category_entity GROUP BY entity_id) ORDER BY `entity_id` ASC;

DELETE FROM `catalog_category_entity_int` WHERE row_id NOT IN (SELECT MAX(row_id) FROM catalog_category_entity GROUP BY entity_id) ORDER BY `entity_id` ASC;

DELETE FROM `catalog_category_entity_text` WHERE row_id NOT IN (SELECT MAX(row_id) FROM catalog_category_entity GROUP BY entity_id) ORDER BY `entity_id` ASC;

DELETE FROM `catalog_category_entity_varchar` WHERE row_id NOT IN (SELECT MAX(row_id) FROM catalog_category_entity GROUP BY entity_id) ORDER BY `entity_id` ASC;
```
running Magento now in 2.4.3 community editions for now I can't find any bugs

Thanks for the help @thomas-kl1

**Comment by thomas-kl1** [comment]
@Khaledhesham regrading @kylianleemkuil comment it seems that the tool is working fine for 2.4

**Comment by kylianleemkuil** [comment]
@thomas-kl1 sure I only never did it before so I made a pull request, no idea if I did it the right way
